environments:
  all:
    pipelines:
      - dotnet-build
      - dotnet-package
      - dotnet-FT
      - python-build
      - python-package
      - python-FT 
      - python-lsp-tests
      - python-release
      - gauge-proto
      - CSharp-Lib
      - CSharp-Core